
services:
  app:
    image: spring-actuator:latest
    build: .
    ports:
      - 8081:8080
    healthcheck:
      test: "wget -nv -t1 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 15s
      start_period: 15s
      retries: 3